### ISSUE TITLE
Up-to-date Defold Support

### ISSUE THREAD

**Issue by CocosGames** [dasannikov/DefoldTypeScript#3]
" (DONE) Auto generate defold.d.ts file with full Defold support. "

How?

**Comment by dasannikov** [comment]
Python script defold_json_to_ts.py generate defold.d.ts file from Defold documentation.

**Comment by dasannikov** [comment]
Maybe i'll prepare better way to update.

**Comment by wilcoverhoeven** [comment]
Ok maybe this is a stupid question, but where can I get the defold json files to generate new up to date type definitions?

**Comment by dasannikov** [comment]
Here is the archive:
http://d.defold.com/archive/{sha1}/engine/share/ref-doc.zip

And {sha1} is from here:
http://d.defold.com/stable/info.json

You can convert it with my Python script:
https://github.com/dasannikov/DefoldTypeScript/blob/master/defold_json_to_ts.py

**Comment by dasannikov** [comment]
Any commits and updates to this repo are welcome!

**Comment by wilcoverhoeven** [comment]
Thx for the reply. I'm  currently evaluating DefoldTypeScript. If I will use it, I will definitely try to contribute where I can.

**Comment by thejustinwalsh** [comment]
I am working on some updates to this over here [@ts-defold/types](https://github.com/ts-defold/types) although the whole thing is much more ambitious than just types.

Thanks @dasannikov for spiking this, I have some updates to the python script that I am going to be submitting a PR for over the weekend. I think it would be very valuable to keep this system up-to-date in case people have disagreeing philosophies with what I am trying to accomplish with @ts-defold.

TypeScriptToLua has made a lot of changes, and there was a considerable amount of work to get the generated types up to date.

Going to be giving you a credit on the stuff I am working on in the readme, but will be re-writing a new type generator in typescript for my projects.

**Comment by dasannikov** [comment]
> will be re-writing a new type generator in typescript for my projects.

Good idea to use TS instead of Python for generator. It will be nice to create on npm package for all stuff including generations on the fly.

**Comment by thejustinwalsh** [comment]
@dasannikov this is what you are looking for https://github.com/ts-defold/type-gen 👍
